osx_image: xcode7
language: objective-c

before_install:
  - git submodule update --init --recursive
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - rake test:ios
  - rake test:osx
  - rake test:xctool_ios
  - rake test:xctool_osx

