osx_image: xcode7
language: objective-c

before_install:
  - git submodule update --init --recursive
  # There is a bug in a formula resulting in update failing if run once, but not the second time
  # See https://github.com/Homebrew/homebrew/issues/45616
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - rake test:ios
  - rake test:osx
  - rake test:xctool_ios
  - rake test:xctool_osx

