name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  cocoapods:
    name: CocoaPods Lint & Danger
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: bundle install
      - run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: rake podspec:lint

  xcode:
    name: Xcode ${{ matrix.xcode }} (${{ matrix.platform }})
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11.7, 12]
        platform: ["macos", "ios", "tvos"]
      fail-fast: false
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: rake test:${{ matrix.platform }}
      - if: ${{ matrix.platform == 'macos' }}
        run: rake test:${{ matrix.platform }}_static

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11.7, 12]
      fail-fast: false
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v2
      - run: rake test:swiftpm

  swiftpm_linux:
    name: SwiftPM, Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift_version: [5.2.5, 5.3.3, 5.4-DEVELOPMENT-SNAPSHOT-2021-01-23-a]
      fail-fast: false
    env:
      SWIFT_VERSION: ${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install swiftenv
        run: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      - run: rake test:swiftpm
