name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  cocoapods:
    name: CocoaPods Lint & Danger
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: gem install bundler:1.17.3 && bundle install
      - run: PODSPEC=1 ./script/travis-script-macos
      - run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

  xcode:
    name: Xcode ${{ matrix.xcode }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [10.3, 11.3.1, 11.4.1]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
      - run: PLATFORM=macos ./script/travis-script-macos
      - run: PLATFORM=macos_static ./script/travis-script-macos
      - run: PLATFORM=ios ./script/travis-script-macos
      - run: PLATFORM=tvos ./script/travis-script-macos

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11.3.1, 11.4.1]
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
      - run: PLATFORM=swiftpm ./script/travis-script-macos
